theme: minima.
title: Camera learn to take a photo of peaople in front and use it to make and collage painting.
author: photo-code.
email: jabrand31@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I want to make a camera that takes photos of people that 
  will be in front of it, and make a database, and later make a great collage. 

# social links
twitter_username: malditopooh # DO NOT include the @ character, or else the build will fail!
github_username:  photo-code # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
